- name: Adiciona arquitetura i386
  shell: "dpkg --add-architecture i386"

- name: update
  apt:
    update_cache: yes

# Please install libstdc++6 32-bit library before installing WithSecure
- name: install dependencies
  apt:
    state: latest
    pkg:
    - libstdc++6:i386
    - python3-pexpect

# Necessário para usar o módulo expect
#- name: install python3-pexpect
#  apt:
#    name: python3-pexpect
#    state: present

- name: Download FSPMS Package
  get_url:
    url: "{{ fsecure_policy_manager_server_url }}"
    dest: /fspms.deb
    mode: 0440

- name: Install FSPMS Package
  apt:
    deb: /fspms.deb

- name: Config FSecure
  expect:
    command: /opt/f-secure/fspms/bin/fspms-config
    responses:
      Host interface HTTP port(.*): "{{ fsecure_http_port }}"
      Host interface HTTPS port(.*): "{{ fsecure_https_port }}"
      Administrator interface port(.*): "{{ fsecure_admin_interface_port }}"
      Restrict access to administrator interface to local machine only(.*): "{{ fsecure_restrict_admin_interface }}"
      Enable Web Reporting(.*): "{{ fsecure_enable_web_reporting }}"
      Web Reporting port(.*): "{{ fsecure_web_port }}"
      Enter password(.*): "{{ fsecure_password }}"
      Confirm password(.*): "{{ fsecure_password }}"

